### ISSUE TITLE
Erreur création pyramide alti?

### ISSUE THREAD

**Issue by jailln** [rok4/docker#2]
J'ai essayé de lancer une génération complète sur un jeu de données altimétrique de la martinique mais le résultat ne me semble pas correct. J'ai dû en faire une mauvaise utilisation ou une mauvaise configuration quelque part.

Voici ce que j'ai fait:

* Pull des images dockers de chaque étape
```
sudo docker pull rok4/pregeneration
sudo docker pull rok4/generation
sudo docker pull rok4/tools
```

* Téléchargement de la BDAlti sur la Martinique: https://geoservices.ign.fr/ressource/154713
* Unzip des données
* Transformation des données en tiff:

```
gdalbuildvrt alti.vrt BDALTIV2_25M_MTQ_0675_1625_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0675_1650_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0700_1600_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0700_1625_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0700_1650_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0725_1600_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0725_1625_MNT_WGS84UTM20_MART87.asc BDALTIV2_25M_MTQ_0725_1650_MNT_WGS84UTM20_MART87.asc
gdalwarp alti.vrt alti.tiff
```

* Vérification du tiff créé:

![image-20221219150528397](https://user-images.githubusercontent.com/16967916/208445149-11db387d-52ac-46a9-a49a-454c62b39049.png)

* Déplacement du tiff dans le dossier: rok4-docker/run/datasets/downloads/ALTI
* Lancement du traitement: `sudo bash be4-generation.sh --all --alti`

Une pyramide est créée mais la plupart des tuiles sont à -99999 sauf une seule tuile qui a des valeurs entre -99999 et -16:

![image-20221219150933543](https://user-images.githubusercontent.com/16967916/208445234-2aa26e97-1e61-47a8-b022-35c99e73d28f.png)

Avez-vous une idée du problème ?

**Comment by Dolite** [comment]
Je viens de refaire la génération de mon côté et les dalles contiennent bien des valeurs cohérentes. Par exemple :
```
gdalinfo -stats 6T.tif 
Driver: GTiff/GeoTIFF
Files: 6T.tif
Size is 4096, 4096
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 4096.0)
Upper Right ( 4096.0,    0.0)
Lower Right ( 4096.0, 4096.0)
Center      ( 2048.0, 2048.0)
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
  Minimum=-99999.000, Maximum=1390.700, Mean=-92963.427, StdDev=25605.273
  Metadata:
    STATISTICS_MAXIMUM=1390.6999511719
    STATISTICS_MEAN=-92963.426880928
    STATISTICS_MINIMUM=-99999
    STATISTICS_STDDEV=25605.273308084
    STATISTICS_VALID_PERCENT=100
```
Vous avez utilisé le fichier de configuration du projet docker ou un que vous avez modifié ? Comment visualisez vous les tuiles de la pyramide, dans QGIS ?

J'ai aussi corrigé la source des données dans le README et ajouté les étapes pour générer le fichier TIF. Merci beaucoup pour cet enrichissement de la documentation.

**Comment by jailln** [comment]
Effectivement, cela doit donc venir de la visualisation dans QGIS, merci. Je vais essayer dans un client web pour voir ce que cela donne, j'ouvrirai une autre issue si besoin.
