### ISSUE TITLE
Erreur lancement du rok4/server avec docker

### ISSUE THREAD

**Issue by jailln** [rok4/docker#4]
Je ne parvient pas à lancer le server rok4 avec docker.

* J'ai essayé de lancer le server rok4 avec docker de la manière suivante:

````
sudo docker pull rok4/server:4.1.0
sudo docker run --publish 9000:9000 rok4/server:4.1.0
````

Mais j'ai les erreurs suivantes:
````
Server start [1]
Loading server configuration from file /etc/rok4/server.json
FATAL: Cannot load server configuration 
FATAL: logger.output 'standard_output' is unknown
````

* J'ai également essayé de le lancer avec le fichier docker-compose.yaml:

Les dockers de datasets qui sont en dépendance n'existent pas avec ce tag là sur la registry docker. En modifiant avec les bons tags, j'ai une erreur nginx. J'ai essayé de lancer nginx avec la config donnée [ici](https://github.com/rok4/docker/tree/develop/run/server) mais nginx ne veut pas redémarrer avec la config donnée. Est-ce la bonne config ? Est-ce que je dois garder certains éléments de la config nginx par défaut et ajouter la config que vous donnez?

**Comment by Dolite** [comment]
Ce souci de configuration a été effectivement repéré. La configuration est fonctionnelle pour la version 5 du serveur, il faut que je duplique la configuration pour chaque version. 

Pour information, la version 5 modifie le mode de chargement des configurations de couches, styles et TMS au niveau du serveur : il charge les styles et les TMS au moment de l'utilisation par une couche (donc potentiellement pas tous), et on fournit une liste des descripteurs de couches que le serveur doit charger. Cela permet d'héberger toutes ces configurations sur du stockage objet et de plus facilement les partager entre des multiples instances du serveur.

Il y a une stack de démonstration du serveur version 5 avec un stockage S3 minio contenant les pyramides, les descripteurs de couches, les styles et les TMS.

**Comment by jailln** [comment]
Super merci! Cela semble se lancer correctement, je vais maintenant tenter de mettre des données derrière.
